### GENERAL SETTINGS ###

# Site settings
title: Roy Xue is Here :)
description: "Roy,Lijun,Xue,Roy Xue,Lijun Xue,薛立君"
analytics: UA-58877422-1
baseurl: "" #important: start with /
url: "http://royxue.me"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#212121" #"#F70031"
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#ffffff" #"#33004D"
  link: "#000000"
  link_hover: "#01b2fe"
  footer_heading: "#000000"
  footer_content: "#000000"


### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: facebook
    url: "https://www.facebook.com/roy.xue29"
  - title: twitter
    url: "https://twitter.com/xljroy"
  - title: instagram
    url: "http://instagram.com/xljroy"
  - title: google-plus
    url: "https://plus.google.com/+RoyXue"
  - title: linkedin
    url: "https://www.linkedin.com/in/royxue"
  - title: github
    url: "https://github.com/royxue"
  - title: picture-o
    url: "https://500px.com/xljroy"

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines:
    - Email=> xljroy#gmail.com
    - Wechat=> xljroy
    - Line=> royxue29
email: xljroy#gmail.com
tel: uknown

# Short text about yourself. Shown in footer on every page and also separately on Home page.
about: "Exploring the world :)"
